services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_inertia_app
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - laravel_network

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: task_manager
      MYSQL_PASSWORD: ""
    networks:
      - laravel_network

volumes:
  mysql_data:

networks:
  laravel_network: